#!/usr/bin/env bash
# Regenerate llms.txt and llms-full.txt for agent ingestion.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

INDEX="$ROOT/llms.txt"
FULL="$ROOT/llms-full.txt"

{
  echo "# Uplink — documentation index for AI agents"
  echo
  echo "> Read AGENTS.md first. Full corpus: llms-full.txt"
  echo "> Repo: https://github.com/absgrafx/Morpheus-Uplink"
  echo
  echo "## Defaults agents must know"
  echo
  echo "- **Uplink ≠ api.mor.org.** Hosted multi-tenant API is api.mor.org / apidocs.mor.org; Uplink is your single-tenant gateway + wallet."
  echo "- **Catalog / bids:** \`ACTIVE_MODELS_URL\` → https://active.mor.org/gateway_models.json ; \`GATEWAY_BIDS_URL\` → https://active.mor.org/gateway_bids.json . Never default to active_models.json / ALL."
  echo "- **Proxy pin:** release compose digest-pins proxy-router (Lumerin) at **v7.11.0** — not \`:latest\`."
  echo "- **Humans** → docs/README.md. **Agents** → AGENTS.md, then llms-full.txt."
  echo "- **Never invent** live prices, catalog size, or contract addresses — cite gateway feeds + docs/01-prerequisites.md."
  echo
  echo "## Core"
  echo
  echo "- [AGENTS.md](AGENTS.md): Hard rules and navigation for agents"
  echo "- [README.md](README.md): Product overview + SecretVM get-running CTA"
  echo "- [DISCLAIMER.md](DISCLAIMER.md): Self-custody and operator risk notice"
  echo "- [LICENSE](LICENSE): MIT (ABSGrafx LLC)"
  echo "- [NOTICE](NOTICE): Third-party licenses (e.g. go-ethereum LGPL)"
  echo "- [llms-full.txt](llms-full.txt): Concatenated operator corpus"
  echo
  echo "## Operator guide"
  echo
  while IFS= read -r f; do
    title="$(grep -m1 '^# ' "$f" | sed 's/^# //')"
    rel="${f#"$ROOT/"}"
    # first non-empty, non-heading, non-nav paragraph-ish line as description
    desc="$(awk '
      /^#/ { next }
      /^\[←/ { next }
      /^---/ { next }
      /^$/ { next }
      { gsub(/\*\*/, ""); print; exit }
    ' "$f" | head -c 160)"
    echo "- [${title}](${rel}): ${desc}"
  done < <(printf '%s\n' docs/README.md docs/01-prerequisites.md docs/02-bootstrap.md \
    docs/03-gui.md docs/04-clients.md docs/05-updates.md docs/06-developers.md docs/USER_GUIDE.md)
  echo
  echo "## Design (optional)"
  echo
  echo "- [.ai-docs/UPLINK_CONCEPT.md](.ai-docs/UPLINK_CONCEPT.md): Architecture and product rationale"
} > "$INDEX"

{
  echo "# Uplink — llms-full.txt"
  echo
  echo "Generated by scripts/gen-llms.sh. Source of truth: AGENTS.md + docs/."
  echo
  echo "================================================================"
  echo
  cat AGENTS.md
  echo
  echo "================================================================"
  echo
  cat DISCLAIMER.md
  echo
  echo "================================================================"
  echo
  cat README.md
  echo
  for f in docs/README.md docs/01-prerequisites.md docs/02-bootstrap.md \
           docs/03-gui.md docs/04-clients.md docs/05-updates.md docs/06-developers.md \
           docs/USER_GUIDE.md; do
    echo
    echo "================================================================"
    echo
    echo "<!-- source: ${f} -->"
    echo
    cat "$f"
    echo
  done
} > "$FULL"

echo "Wrote $INDEX"
echo "Wrote $FULL ($(wc -c < "$FULL") bytes)"
